# Generated by Django 5.0.3 on 2024-03-18 14:33

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullCallData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdr_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('callog_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('extension', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='dbitem',
            name='data',
        ),
        migrations.RemoveField(
            model_name='dbitem',
            name='valid',
        ),
        migrations.CreateModel(
            name='CallPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_location', models.TextField()),
                ('callog_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djapp.fullcalldata')),
            ],
        ),
        migrations.CreateModel(
            name='ConversationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('speaker', models.CharField(max_length=20)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('call_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_items', to='djapp.callpart')),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='djapp_conve_search__cf4ce9_gin')],
            },
        ),
    ]
