# Generated by Django 5.0.3 on 2024-03-18 14:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0002_fullcalldata_remove_dbitem_data_remove_dbitem_valid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fullcalldata',
            name='callog_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
