# Generated by Django 5.0.3 on 2024-03-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0004_conversationitem_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='callpart',
            old_name='callog_uuid',
            new_name='fullcall_id',
        ),
        migrations.RenameField(
            model_name='conversationitem',
            old_name='call_part',
            new_name='callpart_id',
        ),
        migrations.RemoveField(
            model_name='fullcalldata',
            name='callog_uuid',
        ),
        migrations.RemoveField(
            model_name='fullcalldata',
            name='extension',
        ),
        migrations.AddField(
            model_name='callpart',
            name='extension',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fullcalldata',
            name='cdr_uuid',
            field=models.CharField(editable=False, max_length=200),
        ),
    ]
