# Generated by Django 5.0.3 on 2024-03-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0005_rename_callog_uuid_callpart_fullcall_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DBItem',
        ),
        migrations.AddField(
            model_name='callpart',
            name='callpart_uuid',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='callpart',
            name='extension_uuid',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='fullcalldata',
            name='calllog_uuid',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='fullcalldata',
            name='domain',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fullcalldata',
            name='epoch',
            field=models.BigIntegerField(default=0),
        ),
    ]
