# Generated by Django 5.0.3 on 2024-03-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0007_callpart_engine_version_callpart_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callpart',
            name='id',
            field=models.CharField(editable=False, primary_key=True, serialize=False),
        ),
    ]
