# Generated by Django 5.0.3 on 2024-03-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0009_remove_callpart_callpart_uuid_alter_callpart_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fullcalldata',
            name='calllog_uuid',
        ),
        migrations.AlterField(
            model_name='fullcalldata',
            name='id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
