# Generated by Django 5.0.3 on 2024-03-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0011_alter_fullcalldata_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='callpart',
            name='user_id',
            field=models.CharField(default='0493kfe-349dd-3kld30d-349023k'),
            preserve_default=False,
        ),
    ]
