# Generated by Django 5.0.3 on 2024-03-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0012_callpart_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callpart',
            name='user_id',
            field=models.UUIDField(),
        ),
    ]
